services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-gpu-lab
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-gpu-lab
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - prometheus